// <auto-generated />
using System;
using BirdWatching.Shared.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515122448_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BirdWatching.Shared.Model.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddingDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("MainAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainAdminId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirdId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("WatcherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BirdId");

                    b.HasIndex("WatcherId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Watcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainCuratorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MainCuratorId");

                    b.ToTable("Watchers");
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<int>("AdministeredEventsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdministeredEventsId", "AdminsId");

                    b.HasIndex("AdminsId");

                    b.ToTable("EventAdmins", (string)null);
                });

            modelBuilder.Entity("EventWatcher", b =>
                {
                    b.Property<int>("ParticipantsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipatingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantsId", "ParticipatingId");

                    b.HasIndex("ParticipatingId");

                    b.ToTable("EventParticipants", (string)null);
                });

            modelBuilder.Entity("UserWatcher", b =>
                {
                    b.Property<int>("CuratedWatchersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuratorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CuratedWatchersId", "CuratorsId");

                    b.HasIndex("CuratorsId");

                    b.ToTable("WatcherCurators", (string)null);
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Event", b =>
                {
                    b.HasOne("BirdWatching.Shared.Model.User", "MainAdmin")
                        .WithMany("Events")
                        .HasForeignKey("MainAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainAdmin");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Record", b =>
                {
                    b.HasOne("BirdWatching.Shared.Model.Bird", "Bird")
                        .WithMany()
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirdWatching.Shared.Model.Watcher", null)
                        .WithMany("Records")
                        .HasForeignKey("WatcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Watcher", b =>
                {
                    b.HasOne("BirdWatching.Shared.Model.User", "MainCurator")
                        .WithMany("Watchers")
                        .HasForeignKey("MainCuratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainCurator");
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("BirdWatching.Shared.Model.Event", null)
                        .WithMany()
                        .HasForeignKey("AdministeredEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirdWatching.Shared.Model.User", null)
                        .WithMany()
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventWatcher", b =>
                {
                    b.HasOne("BirdWatching.Shared.Model.Watcher", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirdWatching.Shared.Model.Event", null)
                        .WithMany()
                        .HasForeignKey("ParticipatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserWatcher", b =>
                {
                    b.HasOne("BirdWatching.Shared.Model.Watcher", null)
                        .WithMany()
                        .HasForeignKey("CuratedWatchersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirdWatching.Shared.Model.User", null)
                        .WithMany()
                        .HasForeignKey("CuratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("BirdWatching.Shared.Model.Watcher", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
